import { nunito } from "@/styles/fonts";
import Providers from "@/providers/Providers";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

import "@/styles/globals.css";

export const metadata = {
  title: "Woofy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${nunito.className} antialiased `}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
